# site information
name:          "Arc"
description:   "Arc is a multidisciplinary, experimental practice focused on research, collaboration, and data-driven visual systems."
url:           http://arclab.co
permalink:     none

# default settings
defaults:
  -
    scope:
      path:     ''
      type:     posts
    values:
      category: projects
      layout:   post
      is_post:  true

# formatting
kramdown:
  auto_ids: false

sass:
  style: compressed

# gems
gems:
  - jekyll-sitemap
